FROM openjdk:8-jdk-alpine AS builder

COPY src /src

RUN  mkdir /classes \
 && cd src/cores \
 && javac -d /classes/ *.java

FROM openjdk:10-jre-slim

COPY --from=builder /classes/ /app/classes/
WORKDIR app

CMD ["java", "-cp","classes", "cores.ShowCores"]

